# -*- coding: utf-8 -*-
"""상명대 파이썬 2주차 과제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VA3mVCv_l78lQFjaD2ILgBnT8BSFzh9N
"""

def get_radius(prompt):
    r = int(input(prompt))
    return r
prompt = '넓이를 구하고자 하는 원의 반지름은?'
result = get_radius(prompt)

def get_circle_area() :

    s = 3.14 * result * result
    return s

print('반지름', result,'인 원의 넓이 = 3.14 x',result,'x',result,'=', end =  '' )
result2 = get_circle_area()
print(result2)