# -*- coding: utf-8 -*-
"""파이썬 프로그래밍 2주차 과제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ronBPtntHbbuEpX_OmpghgGN5Qu0M2E9
"""

def get_radius(prompt):
    r = int(input(prompt))
    return r

prompt = input('넓이를 구하고자 하는 원의 반지름은?')
result = get_radius(prompt)
print(result)

def get_circle_area() :
    s = 반지름 r인 원의 넓이 =  3.14 *r*r =
    return s

result2 = get_circle_area()
print(result2)

## 틀린 풀이 : 내가 역시 또 한번 input 함수의 프롬프트의 사용에 대해 잘 못 이해하고 있었다.

def get_radius(prompt):
    r = int(input(prompt))
    return r
prompt = '넓이를 구하고자 하는 원의 반지름은?'
result = get_radius(prompt)

def get_circle_area() :

    s = 3.14 * result * result
    return s

print('반지름', result,'인 원의 넓이 = 3.14 x',result,'x',result,'=', end =  '' )
result2 = get_circle_area()
print(result2)

