# -*- coding: utf-8 -*-
"""hw3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cfZtl6MTS50qpo22XyOJgpjBHddhKcX8
"""

# 1. 모듈 import없이 작성해본 코드

discount = int(input('할인율은?'))

dis_A = int(input('A상품의 할인된 가격은?'))
dis_B = int(input('B상품의 할인된 가격은?'))

def get_fixed_price(d_p):
    f_p = d_p / (1- discount/100)
    return f_p

f_A = get_fixed_price(dis_A)
print('A상품의 정가는',int(f_A), '원')
f_B = get_fixed_price(dis_B)
print('B상품의 정가는',int(f_B), '원')

# 2.모듈을 불러와서 작성해본 코드

 from google.colab import files
src = list(files.upload().values())[0]
open('모듈이름.py','wb').write(src)
import 모듈이름

import discount_fixed

discount = int(input('할인율은?'))

dis_A = int(input('A상품의 할인된 가격은?'))
dis_B = int(input('B상품의 할인된 가격은?'))
f_A = get_fixed_price(dis_A)
print('A상품의 정가는',int(f_A), '원')
f_B = get_fixed_price(dis_B)
print('B상품의 정가는',int(f_B), '원')