# -*- coding: utf-8 -*-
"""hw4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1coyHFjKsLF7WfoPT-o7cDB47Q0-p6AIl
"""

def rep_char(c,n):
    print(c * n)

def draw_line_string(str):
    msg1 = f'Hello {str},'
    msg2 = 'welcome to Seoul.'
    nstr = len(msg1) if(len(msg1)>len(msg2))else len(msg2)
    rep_char('-',nstr + 2)
    print(f' {msg1} ')
    print(f' {msg2} ')
    rep_char('-',nstr + 2)

name = input('Input his/her name:')
draw_line_string(name)