# -*- coding: utf-8 -*-
"""hw5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hRuXHWKoPaZwtfMimrTgLpcZaHxMTVx
"""

def read_single_digit(int) :
    if int == 1 :
      return '일'
    elif int == 2 :
      return '이'
    elif int == 3 :
      return '삼'
    elif int == 4 :
      return '사'
    elif int == 5 :
      return '오'
    elif int == 6 :
      return '육'
    elif int == 7 :
      return '칠'
    elif int == 8 :
      return '팔'
    else :
      return '구'


def read_number(int3) :

     if 1<= int3 <= 9 :
        return read_single_digit(int3)
     elif 10<= int3 <= 99 :
        a = str(int3)
        b = a[0]
        c = a[1]
        return f'{read_single_digit(int(b))} {read_single_digit(int(c))}'
     elif 100<= int3 <= 999 :
        x = str(int3)
        y = x[0]
        z = x[1]
        q = x[2]
        return f'{read_single_digit(int(y))} {read_single_digit(int(z))} {read_single_digit(int(q))}'

num = int(input('세 자리 정수 입력:'))
res = read_number(num)
print(f'{res}')