# -*- coding: utf-8 -*-
"""hw6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULkZTTrTyMeXNPSLxbBIcjN9GoRZuTp3
"""

def print_multiplication_table(a, b):
    for i in range(1, 10):
        for j in range(a, b) :
            print(f'{j} x {i} = {j * i:2d}', end='\t')
        print()

print_multiplication_table(2, 6)
print()
print_multiplication_table(6,10)