# -*- coding: utf-8 -*-
"""hw7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R4_Q2eR4e570q14d0I31EYG-AW4fbcxw
"""

shopping_bag = []
sh_quantity = {'사과': 10, '바나나': 2}
while True :
    item = input('상품명?')

    if item == '' :
        break
    shopping_bag.append(item)
    print(f'수량은? {sh_quantity[item]}')
    print(f'장바구니에 {item} {sh_quantity[item]}개가 담겼습니다\n')

print(f'\n>>>장바구니 보기: {sh_quantity}')


print('\n[검색]')
want = input('장바구니에서 확인하고자 하는 상품은?')
print(f'{want}은(는) {sh_quantity[want]}개 담겨있습니다.')