# -*- coding: utf-8 -*-
"""hw8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbI7fVP67LKxmosS-j_FA-uIBpB5d6vn
"""

def buy(dic) :
    print('[구입]')
    a = input('상품명?')

    if  a == '' :
        return False

    elif a not in dic :
        b = int(input('수량?'))
        dic[a] = b
        print(f'장바구니에 {a} {b}개가 담겼습니다.')
        return True

def show(dic) :
    print(f'>>> 장바구니 보기 : {shopping_bag}')

def find(dic) :
    print('[검색]')
    w_t = input('장바구니에서 확인하고자 하는 상품은?')
    if w_t in dic :
        print(f'장바구니에 {w_t}는 {dic[w_t]}개 담겨 있습니다')
    else :
        print(f'장바구니에 {w_t}은(는) 없습니다.')

shopping_bag = {}
while True:
    if buy(shopping_bag) == False :
        break

show(shopping_bag)
find(shopping_bag)