# -*- coding: utf-8 -*-
"""hw9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NyN9F-vPZLCZDJU6IGeg3O9j22gAGGb3
"""

class Point :
    def __init__(self, x=0, y=0) :
        self.__x = x
        self.__y = y

    def show(self) :
        print(f'({self.__x}, {self.__y})')

    def set(self, x, y) :
        self.__x = x
        self.__y = y

    def get(self) :
        return (self.__x, self.__y)


lt = Point()
rb = Point()

class Rectangle :
    def __init__(self, x1, y1, x2, y2) :
        self.lt_x = x1
        self.lt_y = y1
        self.rb_x = x2
        self.rb_y = y2

    def show(self) :
        print(f'좌측 상단 꼭짓점이 {(self.lt_x, self.lt_y)}이고 우측 하단 꼭짓점이 {(self.rb_x, self.rb_y)}인 사각형입니다.')

    def getWidth(self) :
        return self.rb_x - self.lt_x

    def getHeight(self) :
        return self.rb_y - self.lt_y

    def getArea(self) :
        return (self.rb_x - self.lt_x) * (self.rb_y - self.lt_y)

    def getPerimeter(self):
        return 2*((self.rb_x - self.lt_x) + (self.rb_y - self.lt_y))

r1 = Rectangle(5,5,20,10)
a = r1.getArea()
p = r1.getPerimeter()

r1.show()
print(f'\n넓이는 {a}, 둘레는 {p}')