# -*- coding: utf-8 -*-
"""hw.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p25CvFOlL6sjBtaJInu2a695hcfLcmTt
"""

def exchange(money) :

    n500 = money // 500
    x = money %500
    n100 = x // 100
    x = x %100
    n50 = x // 50
    x = x %50
    n10 = x //10

    print('500원 동전의 개수:',n500, end='\n')
    print('100원 동전의 개수:',n100, end='\n')
    print('50원 동전의 개수:',n50, end='\n')
    print('10원 동전의 개수:',n10)

def get_integer(prompt):
    res = int(input(prompt))
    return res

money = get_integer('동전으로 교환하고자 하는 금액은?')
exchange(money)